name: CD-Self-Hosted-Runner

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull repo
        run: |
          if [ ! -d ~/skillpulse ]; then
            git clone https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git ~/skillpulse
          else
            cd ~/skillpulse
            git pull origin main
          fi

      - name: Check .env if not exists
        run: |
          if [ ! -f ~/skillpulse/.env ]; then
            cat > ~/skillpulse/.env << 'EOF'
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            DB_HOST=${{secrets.DB_HOST}}
            DB_USER=${{vars.DB_USER}}
            DB_PASSWORD=${{secrets.DB_PASSWORD}}
            DB_NAME=${{vars.DB_NAME}}
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            echo ".env created from secrests"
          fi

      - name: Deploy
        run: |
          cd ~/skillpulse
          docker compose pull
          docker compose up -d
          docker image prune -f
