name: Deploy to EC2 Server

on: 
  push:
    branches: [main]
  workflow_dispatch: 
 
jobs:
  CI:
    name: Build and Push to DockerHub
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  CD:
    name: Deploy to EC2 Server
    needs: [CI]
    uses: ./.github/workflows/cd-ec2.yml
    secrets: inherit
