name: Deploy to Self Hosted Runner

on: 
  push:
    branches: [main]
 
jobs:
  CI:
    uses: ./.github/workflows/ci/ci.yml
    secrets: inherit

  CD:
    needs: [CI]
    uses: ./.github/workflows/cd/cd-self-hosted.yml
    secrets: inherit
